# Global Kafka configurations
bootstrap_server: "localhost:9092"
schema_server: "http://localhost:8081/"
use_avro: False
use_ssl: False
ssl_cafile: " "
ssl_keyfile: " "
ssl_password: "PASSWORD"
ssl_security_protocol: "SASL_SSL"
ssl_sasl_mechanism: "PLAIN"
sasl_plain_username: "PLAIN_USERNAME"
sasl_plain_password: "PLAIN_PASSWORD"

# list of topics added
list_of_topics: 
  - name: me
    kafka_topic: "1"
    ros_topic: " "
    ros_msg_type: " "
    avro_subject: " "

  - kafka_topic: "2"
    ros_topic: " "
    ros_msg_type: " "
    avro_subject: " "